app = "realtime-voice-translate-frontend"
primary_region = "mad"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = [ "app" ]

[build]
  builder = "paketobuildpacks/builder:base"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024

[env]
  PORT=3000
  VITE_API_URL="https://realtime-voice-translate.fly.dev"